### ISSUE TITLE
train code

### ISSUE THREAD

**Issue by yyhlvdl** [ayooshkathuria/pytorch-yolo-v3#13]
@ayooshkathuria , hi, thanks a lot for your work. And I am waiting for the train code. Could you tell me when the train code is available, plz? Because I want to be lazy. Hope this quest not bother you.

**Comment by ayooshkathuria** [comment]
I was busy with my college thesis and moving my stuff home 400 miles from college. Been busy like hell. Will start working on the train code soon.

**Comment by yyhlvdl** [comment]
I feel sorry for my quest, good luck.
