### ISSUE TITLE
Error when loading own trained weight file

### ISSUE THREAD

**Issue by raggot** [ayooshkathuria/pytorch-yolo-v3#14]
Hi,

I tested loading my own trained weights which I got using darknet's official guide. Basically, I substituted `yolov3.weights` with my own `yolov3-own.weights` as the default `--weights` argument in the code.

This is console's output:

```
Loading network.....
Traceback (most recent call last):

  File "<ipython-input-3-1d1acba7b8a9>", line 1, in <module>
    runfile('/home/raggot/Projects/test/detect.py', wdir='/home/raggot/Projects/test')

  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/usr/local/lib/python3.5/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/raggot/Projects/test/detect.py", line 89, in <module>
    model.load_weights(args.weightsfile)

  File "/home/raggot/Projects/test/darknet.py", line 448, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)

  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 230, in view_as
    return self.view(tensor.size())

RuntimeError: invalid argument 2: size '[256 x 128 x 3 x 3]' is invalid for input with 37347 elements at /pytorch/aten/src/TH/THStorage.c:41
```

What is the problem here? What are the 37347 elements the error refers to?

Thanks.

**Comment by ayooshkathuria** [comment]
On how many classes have you trained the network. You also need to change the shape of Network to reflect the change in number of classes. Please provide more info as to exactly what else have you changed other than weights file if your weights file hasn't been trained on COCO.

**Comment by raggot** [comment]
That's a good point. I trained it using VOC, which actually has 20 classes defined (at least in Darknet's default configuration). 

If that's so however I'd find it strange, because my network was trained (like your default assumption supposes) on 416x416 size. This is the beginning of the darknet training cfg file I used:

> [net]
> # Testing
> # batch=1
> # subdivisions=1
> # Training
> batch=64
> subdivisions=64
> width=416
> height=416
> channels=3
> momentum=0.9
> decay=0.0005
> angle=0
> saturation = 1.5
> exposure = 1.5
> hue=.1
> 
> learning_rate=0.001
> burn_in=1
> max_batches = 50200
> policy=steps
> steps=40000,45000
> scales=.1,.1

I'm still generally puzzled about what the `[256 x 128 x 3 x 3]` actually refers to, though. Do you know what they represent, and what values are expected?

Thanks for your time and work you share.

**Comment by ayooshkathuria** [comment]
I know what these guys represent, but since Pascal has 20 classes, the "yolo" layer in your config file will have a different output. The reason I say that because the depth of convolutional layer just before the yolo layer is (3 x (5 + C)). You will see it as 255 in yolo-v3.config file., which works for COCO. For, PASCAL VOC, it would be 75, (3 * (5 + 20)). Plus the anchors would be different since it's a different dataset. I suggest you swap the config file with yolo-v3-voc.cfg from darknet's official github repo.

**Comment by ayooshkathuria** [comment]
256 x 128 x 3 x 3 prolly refers to size of convolutional feature map. Will have to dig deeper.

**Comment by raggot** [comment]
Thanks for the quick reply. 

I actually am using darknet's official repo's `yolo-v3-voc.cfg`. I only changed the `batch_size` and the `burn_in` parameters to be able to run the training on my GPU and to get results in a reasonable time for testing. Config-wise, no other change whatsoever.

Tonight I will try to correct the number of classes and see if the problem is solved.

**Comment by ayooshkathuria** [comment]
Did you use yolo-v3-voc.cfg for running on my implementation as well?

**Comment by raggot** [comment]
Whoops.. Overlooked that! I guess that's the issue :+1: 
I'll update the issue tonight after I can test it.

Thanks!

**Comment by raggot** [comment]
You were right. That 'fixed' it. I put it in brackets because another problem arose and I'm not sure what's the actual issue, but I'll make a separate ticket for that one, as this one found its answer.

Thanks! I'll make another issue soon about the next problem.

**Comment by ahkarami** [comment]
Dear @raggot,
Would you please release the trained weights of YOLO v3 on **PASCAL VOC** data set?
