### ISSUE TITLE
Why doesn't it save the result which has predicting box of images in directory imgs?

### ISSUE THREAD

**Issue by Suncheng2019** [ayooshkathuria/pytorch-yolo-v3#148]
I have ran the project, I just get the console print but not the images after detecting. I want to get the images with predecting boxes, emmm what should I do?
Thank you very much!

**Comment by HansiIMW** [comment]
Hi, you could include code in class(write) to save the coordinates and label to a txt file.

**Comment by Suncheng2019** [comment]
> Hi, you could include code in class(write) to save the coordinates and label to a txt file.

Thank you, I have worked it out.
