### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by ErnstTmp** [ayooshkathuria/pytorch-yolo-v3#16]
Thanks for creating this, it looks great! I would love to use it, but I would need the possibility to train according to my needs - can you probably give an estimate when training will be available?

Thanks and kind regards
Ernst

**Comment by yyhlvdl** [comment]
issue#13 is my quest, the author is busy now. We may should wait or write code ourselves.

**Comment by ErnstTmp** [comment]
sorry, I did not see your question.

@ayooshkathuria  good luck!
