### ISSUE TITLE
yolov3-tiny doesnt work

### ISSUE THREAD

**Issue by skrish13** [ayooshkathuria/pytorch-yolo-v3#17]
i have the cfg and weights file. I tried to run,  but it gives this error 

> File "object_detection/darknet.py", line 323, in forward
>     x = torch.cat((map1, map2), 1)
> RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 416 and 832 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:111
>

**Comment by themathgeek13** [comment]
The main issue is that the configuration file for yolov3-tiny includes [maxpool] which is not included in this code. Just add the following code to the create_modules function in darknet.py:

```
elif (x["type"] == "maxpool"):
    size = int(x["size"])
    stride = int(x["stride"])
    if stride>1:
        maxpool = nn.MaxPool2d(size, stride=stride)
        module.add_module("maxpool_{}".format(index), maxpool)
    else:
        module.add_module("maxpool_{}".format(index), MaxPoolStride1())
```

The class MaxPoolStride1 is defined as:
```
class MaxPoolStride1(nn.Module):
    def __init__(self):
        super(MaxPoolStride1, self).__init__()

    def forward(self, x):
        x = F.max_pool2d(F.pad(x, (0,1,0,1), mode='replicate'), 2, stride=1)
        return x
```

Finally, at the top of the forward function in the Darknet class, change the following line:
### BEFORE
```
if module_type=="convolutional" or module_type=="upsample":
    x = self.module_list[i](x)
```
### AFTER
```
if module_type=="convolutional" or module_type=="upsample" or module_type=="maxpool":
    x = self.module_list[i](x)
```

I was able to implement these changes by having a look at this repository: https://github.com/marvis/pytorch-yolo2.

Hope this helps!

**Comment by ayooshkathuria** [comment]
This issue has been fixed now. Please pull the latest code. The problem arose due the fact that the full YOLO v3 arch doesn't have max pooling, and I hadn't implemented it. But, Tiny YOLO v3 does have maxpooling, and I implemented it and that fixed the issue. 

Thanks for reporting though.

**Comment by AntoineGerardeaux** [comment]
Can your share your implementation ? I need maxpooling add
