### ISSUE TITLE
Does this repo support python2.7?if not ,how can I change code to adapt python2.7?

### ISSUE THREAD

**Issue by gittigxuy** [ayooshkathuria/pytorch-yolo-v3#2]

**Comment by ayooshkathuria** [comment]
Not as of yet. It's on my list. But prioritising support for training and PyTorch 0.4 compatibility before I tackle 2.7 compatibility. Though there isn't an awful lot that needs to be changed. 

One of the biggest problems with backward compatibility in deep learning based repos I've found online is the division operator in Python 3.5 produces floats whereas it produces ints in 2.7. I have taken care of that, so no worries on that regard.

You can try running the code and fixing errors as they go by and if possible, make a pull request which will be highly appreciated. If that doesn't happen, I'll try to tackle the issue in the coming week, but as I say, more pressing issues at hand such as training and PyT 0.4.
