### ISSUE TITLE
When I run detect.py,I meet this problem.what should I do?

### ISSUE THREAD

**Issue by gittigxuy** [ayooshkathuria/pytorch-yolo-v3#3]
![default](https://user-images.githubusercontent.com/15090557/38795904-480ff276-418c-11e8-8c27-a45bc3789621.png)

**Comment by ayooshkathuria** [comment]
Please tell your specs. Your version of OpenCV, python and PyTorch.  Perhaps try commenting the line 151 in `detect.py`. Also, I can't seem to recreate this error. Runs fine on  

Possible ways you can find what's going wrong.

Try printing the value of variable `inp_dim` at line 150 in `detect.py` and inspecting it. Plus, I expect this program to arise if opencv cannot read properly the file `dog-cycle-car.png`. You sure you have that image in your repo folder. Try re-downloading maybe. Could also try renaming `dog-cycle-car.png` to `dog-cycle-car.jpg` and accordingly changing line 32 in `detect.py`. 

Could also try update opencv by running 

```
conda install opencv
```
