### ISSUE TITLE
why detect.py isn't saving predicted images with boxes in 'det'?

### ISSUE THREAD

**Issue by angelsingh** [ayooshkathuria/pytorch-yolo-v3#33]
Though 'det' is automatically created but images with predicted boxes are not saved in it..can you plz help out..

**Comment by angelsingh** [comment]
Oh ho my bad..I made a mistake..So, closing the issue..& thankyou soo much for awesome articles on yolo v3..

**Comment by KYZQ** [comment]
In windows ，path separator is ’\' , but in original code , just use '/', that cause no image out problem

detect.py    line 302:
det_names = pd.Series(imlist).apply(lambda x: "{}/det_{}".format(args.det,x.split("/")[-1]))

you need make some change if your system is windows

**Comment by angelsingh** [comment]
Yeah that isn't working out but when detect.py is run on individual image output does gets saved in det folder...just need to run the below given line on terminal:

python detect.py --images imgs/aeroplanes.jpg --det det
