### ISSUE TITLE
what is the function of  "img_ = img[:,:,::-1].transpose((2,0,1)).copy()" code in prep_image func

### ISSUE THREAD

**Issue by hwijunkwon** [ayooshkathuria/pytorch-yolo-v3#39]
Hello, i found a line 

img_ = img[:,:,::-1].transpose((2,0,1)).copy() 

Is this code for transposing BGR to RGB ?

If so, it should be changed.

Let me know.

thanks

**Comment by CaptainEven** [comment]
@hwijunkwon Hi, i 'm pretty sure about what this line of code mean, is 'img[:,:,::-1]' already done the transposing from BGR to RGB? So, What dose the following transpose(2,0,1) do? Can you give me any hint? Thx!

**Comment by CaptainEven** [comment]
@hwijunkwon Hi, i 'm not pretty sure about what this line of code mean. Is 'img[:,:,::-1]' already done the transposing from BGR to RGB? So, What dose the following transpose(2,0,1) do? Can you give me any hint? Thx!

**Comment by tycallen** [comment]
Those code is dealing with opencv image format, which is [H * W * C]. And the opencv channles are BGR, `img[:,:,::-1]` is convert to RGB. ` transpose(2,0,1)` is to change them to [C * W * H].

**Comment by SravanChittupalli** [comment]
Why are we converting it to [C*H*W]? As i have seen input to YOLO is [BatchSize, W, H, C]?
Where am I going wrong?

**Comment by RichardObi** [comment]
>  ` transpose(2,0,1)` is to change them to [C * W * H].

I think _[C * H * W]_ was meant here instead of _[C * W * H]_
