### ISSUE TITLE
no outputs

### ISSUE THREAD

**Issue by hktxt** [ayooshkathuria/pytorch-yolo-v3#43]
S E:\condaDev\pytorch-yolo-v3-master> python detect.py --images imgs --det det
Loading network.....
Network successfully loaded
C:\Users\Max\Anaconda3\envs\Pytorch\lib\site-packages\torch\nn\modules\upsampling.py:122: UserWarning: nn.Upsampling is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.Upsampling is deprecated. Use nn.functional.interpolate instead.")
E:\condaDev\pytorch-yolo-v3-master\imgs\dog.jpg predicted in  1.411 seconds
Objects Detected:    bicycle truck dog
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\eagle.jpg predicted in  1.386 seconds
Objects Detected:    bird
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\giraffe.jpg predicted in  1.414 seconds
Objects Detected:    zebra giraffe giraffe
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\herd_of_horses.jpg predicted in  1.420 seconds
Objects Detected:    horse horse horse horse
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\img1.jpg predicted in  1.406 seconds
Objects Detected:    person dog
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\img2.jpg predicted in  1.410 seconds
Objects Detected:    train
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\img3.jpg predicted in  1.407 seconds
Objects Detected:    car car car car car car car truck traffic light
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\img4.jpg predicted in  1.402 seconds
Objects Detected:    chair chair chair clock
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\messi.jpg predicted in  1.401 seconds
Objects Detected:    person person person sports ball
----------------------------------------------------------
E:\condaDev\pytorch-yolo-v3-master\imgs\person.jpg predicted in  1.542 seconds
Objects Detected:    person dog horse
----------------------------------------------------------

SUMMARY
----------------------------------------------------------
Task                     : Time Taken (in seconds)

Reading addresses        : 0.000
Loading batch            : 1.614
Detection (11 images)    : 15.668
Output Processing        : 0.000
Drawing Boxes            : 0.005
Average time_per_img     : 1.571
----------------------------------------------------------

no outputs found in det folder

**Comment by ytshih12907** [comment]
so, why no output in det folder? I have the same question, too.

**Comment by hktxt** [comment]
@ytshih12907  solved. path problem. see https://github.com/ayooshkathuria/pytorch-yolo-v3/issues/38
