### ISSUE TITLE
output issues between windows and linux

### ISSUE THREAD

**Issue by hktxt** [ayooshkathuria/pytorch-yolo-v3#44]
It totally works in linux, output images saved in det folder.
However, no output images saved in det folder on windows, even it detects objects in images.
it runs correctly in detection part, but save output images into folder failed.
How to solve this problem?

**Comment by nm46nm** [comment]
> It totally works in linux, output images saved in det folder.
> However, no output images saved in det folder on windows, even it detects objects in images.
> it runs correctly in detection part, but save output images into folder failed.
> How to solve this problem?

So how to?
