### ISSUE TITLE
NameError: name 'im_dim' is not defined`

### ISSUE THREAD

**Issue by electron64** [ayooshkathuria/pytorch-yolo-v3#62]
Hello, i get this error while running python cam_demo.py
I m running this on windows via anaconda.
Any idea how to fix it?

`Traceback (most recent call last):
  File "cam_demo.py", line 123, in <module>
    im_dim = im_dim.cuda()
NameError: name 'im_dim' is not defined`

**Comment by ht-dep** [comment]
delete this row

**Comment by madhu-korada** [comment]
on 122 line there is a comment, remove that comment and it works.

**Comment by electron64** [comment]
Thank you it s fixed, by removing this line.

**Comment by jalaldev1980** [comment]
Hello,

I am getting the same problem. 

I removed the comment on line 122 then I got diffrent error 

  File "cam_demo.py", line 119
    im_dim = torch.FloatTensor(dim).repeat(1,2)
                                                                      ^
IndentationError: unindent does not match any outer indentation level


any one cad advice

**Comment by sucy171106** [comment]
+1
