### ISSUE TITLE
RuntimeError: Input type (CUDAFloatTensor) and weight type (CUDAHalfTensor) should be the same

### ISSUE THREAD

**Issue by Ssrzbao** [ayooshkathuria/pytorch-yolo-v3#7]
When I run vedio_demo.py,I meet the problem.Can you teach me how to deal with it?

**Comment by ayooshkathuria** [comment]
You sure video_demo.py is being run. Maybe you're running `video_demo_half.py`?

**Comment by ayooshkathuria** [comment]
Also please tell, on which line exactly are you getting the error?

**Comment by Ssrzbao** [comment]
Because I have download the yolov3.weights which with CUDAFloatTensor. Then I transformed the code all CUDAHalfTensor into CUDAFloatTensor,and solved the problem.
