### ISSUE TITLE
Have problem running the demo.py

### ISSUE THREAD

**Issue by jindongwang** [ayooshkathuria/pytorch-yolo-v3#8]
I run the code on a Linux server with Pytorch 0.4.0. And I get the following error:
![qq 20180427212738](https://user-images.githubusercontent.com/6158206/39364827-d3b2baa6-4a61-11e8-9a88-698d04936194.png)

I use the py4 branch. Please tell me how to run this.

**Comment by ayooshkathuria** [comment]
Are you using a different cfg? The weights are not getting loaded properly. Have a look at the size of your weights file. It should be 237 mb. Try redownloading it. I can't think of anything else than trying to load an incorrect amount of weights in a convolutional layer that takes a different number of layers.

**Comment by ayooshkathuria** [comment]
Try running it with the master branch. It is compatible with 0.4 too.

**Comment by jindongwang** [comment]
@ayooshkathuria You are right. i redownloaded the weights and now it works! Thank you!
